import { StyleSheet } from 'react-native';
import Gui from './gui';
import Colours from './colours';

export function FormStyle(){
    return(
        StyleSheet.create({
            container: {
                flex: 1,
            },
            message: {
                width: '100%',
                backgroundColor: '#59b300',
                padding: 20,
            },
            header: {
                paddingTop: 60,
                paddingLeft: Gui.screen.width * 0.1,
                paddingRight: Gui.screen.width * 0.1,
                zIndex: 3,
                backgroundColor: Gui.container.backgroundColor,
                height: Gui.screen.height * 0.12,
                flexDirection: 'row',
                alignContent: 'space-between',
            },
            headerTitle: {
                fontFamily: 'Volte',
                alignItems: 'center',
                textAlign: 'center',
                textAlignVertical: 'center',
                fontWeight: 'bold',
                fontSize: Gui.screen.height * 0.028,
                marginRight: Gui.screen.width * 0.20,
            },
            scroll: {
                backgroundColor: Colours.white,
            },
            
            inputTitle: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'top',
                marginTop: Gui.screen.height * 0.02,
                marginLeft: Gui.screen.width * 0.1,
                fontSize: Gui.screen.height * 0.02,
                height: Gui.screen.height * 0.04,
                width: Gui.screen.width * 0.8,
                color: Colours.default,
            },
            dropDownText: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'center',
                fontSize: Gui.screen.height * 0.02,
                backgroundColor: Colours.white,
            },
            dropDownPlaceholderText: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'center',
                fontSize: Gui.screen.height * 0.02,
                color: Colours.grey,
            },
            dropDownBody: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'center',
                marginLeft: Gui.screen.width * 0.1,
                fontSize: Gui.screen.height * 0.02,
                width: Gui.screen.width * 0.8,
            },
            textInputContainer: {
                fontFamily: "Volte",
                marginLeft: Gui.screen.width * 0.1,
                height: Gui.screen.height * 0.055,
                width: Gui.screen.width * 0.8,
                borderRadius: 10,
                borderWidth: 1,
                borderColor: Colours.grey,
            },
            textInput: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'top',
                fontSize: Gui.screen.height * 0.02,
                height: Gui.screen.height * 0.05,
                color: Colours.default,
            },
            listView: {
                marginTop: 1,
                marginLeft: Gui.screen.width * 0.1,
                width: Gui.screen.width * 0.8,
                borderRadius: 10,
                borderWidth: 1,
                borderColor: Colours.default,
            },
            
            description: {
                fontFamily: "Volte",
                flexShrink: 1,
                marginLeft: Gui.screen.width * 0.01,
                fontSize: Gui.screen.height * 0.02,
            },
            row: {
                padding: 0,
                height: Gui.screen.height * 0.045,
            },
            inputText: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'center',
                marginLeft: Gui.screen.width * 0.1,
                fontSize: Gui.screen.height * 0.02,
                height: Gui.screen.height * 0.05,
                width: Gui.screen.width * 0.8,
                color: Colours.default,
                borderRadius: 10,
                borderWidth: 1,
                borderColor: Colours.default,
                padding: 10,
            },
            inputTextDescription: {
                fontFamily: "Volte",
                textAlign: 'left',
                textAlignVertical: 'top',
                marginLeft: Gui.screen.width * 0.1,
                fontSize: Gui.screen.height * 0.02,
                height: Gui.screen.height * 0.10,
                width: Gui.screen.width * 0.8,
                color: Colours.default,
                borderRadius: 10,
                borderWidth: 1,
                borderColor: Colours.default,
                padding: 10,
            },
            date: {
                textAlign: 'left',
                textAlignVertical: 'center',
                marginTop: Gui.screen.height * 0.005,
                marginLeft: Gui.screen.width * 0.1,
                fontSize: Gui.screen.height * 0.02,
                height: Gui.screen.height * 0.05,
                width: Gui.screen.width * 0.8,
                color: Colours.default,
                borderRadius: 10,
                borderWidth: 1,
                borderColor: Colours.default,
                fontWeight: 'normal',
                padding: 10,
            },
            dateText: {
                fontFamily: "Volte",
                fontSize: Gui.screen.height * 0.02,
            },
            errorView: {
                flexDirection: 'row',
                marginLeft: Gui.screen.width * 0.1,
                marginBottom: Gui.screen.height * 0.01,
                width: Gui.screen.width * 0.8,
                alignContent: 'center',
            },
            errorText: {
                fontFamily: "Volte",
                textAlign: 'center',
                textAlignVertical: 'center',
                marginTop: Gui.screen.height * 0.005,
                marginBottom: Gui.screen.height * 0.005,
                fontSize: Gui.screen.height * 0.02,
                height: Gui.screen.height * 0.1,
                width: Gui.screen.width * 1,
                color: Colours.red,
                flex: 1,
                flexWrap: 'wrap',
            },
            submit: {
                marginTop: Gui.screen.width * 0.1,
                marginLeft: Gui.screen.width * 0.1,
                marginBottom: Gui.screen.height * 0.01,
                justifyContent: 'center',
                alignItems: 'center',
                height: Gui.screen.height * 0.05,
                width: Gui.screen.width * 0.8,
                borderRadius: Gui.button.borderRadius,
                borderWidth: Gui.button.borderWidth,
                backgroundColor: Colours.koha_orange,
                borderColor: Colours.koha_orange,
            },
            cancel: {
                marginTop: Gui.screen.width * 0.03,
                marginLeft: Gui.screen.width * 0.1,
                marginBottom: Gui.screen.height * 0.05,
                justifyContent: 'center',
                alignItems: 'center',
                height: Gui.screen.height * 0.05,
                width: Gui.screen.width * 0.8,
                borderRadius: Gui.button.borderRadius,
                borderWidth: 3,
                borderColor: Colours.koha_orange,
            },
            submitText: {
                fontSize: 20,
                fontWeight: 'bold',
                color: Colours.white,
                fontFamily: "Volte",
            },
            cancelText: {
                color: Colours.koha_orange,
                fontSize: 20,
                fontWeight: 'bold',
                fontFamily: "Volte",
            },
            
            end: {
                height: '5%',
            },
            buttonContainer:{
                justifyContent: 'space-around',
            }
        })
    )
}